# Generated by Django 5.1.3 on 2024-11-29 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0004_alter_rating_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='email_address',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='rating',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_app.recipe'),
        ),
    ]
