# Generated by Django 5.1.3 on 2024-12-01 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0005_rename_email_address_feedback_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='ai_assistance_feedback',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='content_quality_rating',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='ease_of_use_rating',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='recipe_search_experience_rating',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user_interface_rating',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user_name',
        ),
        migrations.AddField(
            model_name='feedback',
            name='additional_comments',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='chatbot_helpfulness',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
        migrations.AddField(
            model_name='feedback',
            name='chatbot_response_speed',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
        migrations.AddField(
            model_name='feedback',
            name='ease_of_navigation',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
        migrations.AddField(
            model_name='feedback',
            name='favorite_feature',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='least_favorite_feature',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='ratings_comments_usefulness',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
        migrations.AddField(
            model_name='feedback',
            name='recipe_content_quality',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
        migrations.AddField(
            model_name='feedback',
            name='recipe_search_experience',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='visual_appeal',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='overall_rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='suggestions_for_improvement',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='would_recommend',
            field=models.BooleanField(default=False),
        ),
    ]
