# Generated by Django 5.1.3 on 2024-12-02 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0009_chatbotquery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbotquery',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='chatbotquery',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='chatbotquery',
            name='success',
        ),
        migrations.RemoveField(
            model_name='chatbotquery',
            name='updated_at',
        ),
    ]
